version: '2'

services:

  service-eureka:
    image: eureka-server-image
    container_name: eureka-server
    ports:
      - "8761:8761"

  service-zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - "9411:9411"

  service-elasticsearch:
    image: elasticsearch
    container_name: elasticsearch-server

  service-kibana:
    image: kibana
    container_name: kibana-server
    links:
     - service-elasticsearch:elasticsearch
    ports:
     - "5601:5601"

  service-rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
     - "5672:5672"
     - "15672:15672"

  service-turbine:
    image: turbine-server-image
    container_name: turbine-server
    ports:
     - "9090:8080"